# Generated by Django 2.0.3 on 2018-03-29 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Sentence')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tagname')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
            ],
        ),
        migrations.AddField(
            model_name='sentence',
            name='tag',
            field=models.ManyToManyField(to='app.Tag', verbose_name='tag'),
        ),
    ]
