# Generated by Django 2.0.3 on 2018-04-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sentence',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['ordering', 'pk']},
        ),
        migrations.AddField(
            model_name='tag',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Tagname'),
        ),
    ]
